import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** Primary key: random UUID generated by Postgres (`gen_random_uuid()`). */
export const id = () => uuid().primaryKey().defaultRandom();

/** `created_at` / `updated_at`, both timestamptz. `updated_at` is bumped by Drizzle on every update. */
export const timestamps = () => ({
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
export const tstz = () => timestamp({ withTimezone: true });
